// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TvMaze.Scraper.Data;

namespace TvMaze.Scraper.Synchronizer.Migrations
{
    [DbContext(typeof(TvMazeDbContext))]
    [Migration("20200607165435_intialMigration")]
    partial class intialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TvMaze.Scraper.Data.Entities.Cast", b =>
                {
                    b.Property<int>("Id");

                    b.Property<DateTime?>("Birthday");

                    b.Property<string>("Name");

                    b.Property<string>("RawResponse");

                    b.HasKey("Id");

                    b.ToTable("Casts");
                });

            modelBuilder.Entity("TvMaze.Scraper.Data.Entities.TvShow", b =>
                {
                    b.Property<int>("Id");

                    b.Property<string>("Name");

                    b.Property<string>("RawResponse");

                    b.HasKey("Id");

                    b.ToTable("TvShows");
                });

            modelBuilder.Entity("TvMaze.Scraper.Data.Entities.TvShowCast", b =>
                {
                    b.Property<int>("TvShowId");

                    b.Property<int>("CastId");

                    b.HasKey("TvShowId", "CastId");

                    b.HasIndex("CastId");

                    b.ToTable("TvShowCast");
                });

            modelBuilder.Entity("TvMaze.Scraper.Data.Entities.TvShowCast", b =>
                {
                    b.HasOne("TvMaze.Scraper.Data.Entities.Cast", "Cast")
                        .WithMany("TvShowCasts")
                        .HasForeignKey("CastId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TvMaze.Scraper.Data.Entities.TvShow", "TvShow")
                        .WithMany("TvShowCasts")
                        .HasForeignKey("TvShowId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
